/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'

const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/categorias': typeof CategoriasRouteWithChildren
  '/categorias/$slug': typeof CategoriasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cardapio' | '/categorias' | '/categorias/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cardapio' | '/categorias' | '/categorias/$slug'
  id: '__root__' | '/' | '/cardapio' | '/categorias' | '/categorias/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardapioRoute: typeof CardapioRoute
  CategoriasRoute: typeof CategoriasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
  }
}

interface CategoriasRouteChildren {
  CategoriasSlugRoute: typeof CategoriasSlugRoute
}

const CategoriasRouteChildren: CategoriasRouteChildren = {
  CategoriasSlugRoute: CategoriasSlugRoute,
}

const CategoriasRouteWithChildren = CategoriasRoute._addFileChildren(
  CategoriasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardapioRoute: CardapioRoute,
  CategoriasRoute: CategoriasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
